// Grilles de pixels des sprites — l'« atelier d'art » du jeu.
// Caractères : '.' transparent · 'k' contour · 'w' blanc (yeux)
//   corps : 's' peau, 'S' peau ombrée · cheveux : 'h', 'H' · tenue : 'o', 'O'
//   ennemis : 'b' base, 'B' base ombrée, 'x' accent
export type PixelMap = string[];

// ————— Personnage (12 × 14), en couches : corps → tenue → cheveux —————

export const BODY: PixelMap = [
  '....kkkk....',
  '...kssssk...',
  '..kssssssk..',
  '..kswsswsk..',
  '..kssssssk..',
  '...kSssSk...',
  '....kssk....',
  '..kssssssk..',
  '..kssssssk..',
  '..kssssssk..',
  '...kssssk...',
  '...ks..sk...',
  '...ks..sk...',
  '...kk..kk...',
];

export const HAIR_STYLES: Record<string, PixelMap> = {
  court: [
    '....hhhh....',
    '...hhhhhh...',
    '..hhhHHhhh..',
    '..hh....hh..',
  ],
  long: [
    '....hhhh....',
    '...hhhhhh...',
    '..hhhhhhhh..',
    '..hh....hh..',
    '..hh....hh..',
    '..hH....Hh..',
    '..hh....hh..',
  ],
  tresse: [
    '....hhhh....',
    '...hhhhhh...',
    '..hhhhhhhh..',
    '..hh....hh..',
    '...h........',
    '...H........',
    '...h........',
    '...H........',
  ],
  chauve: [
    '............',
    '....hh......',
  ],
};

export const OUTFIT_STYLES: Record<string, PixelMap> = {
  tunique: [
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '..oooooooo..',
    '..oooooooo..',
    '..oOOOOOOo..',
    '...oooooo...',
    '...oo..oo...',
  ],
  armure: [
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '.OooooooooO.',
    '..oOOooOOo..',
    '..oooooooo..',
    '...OOOOOO...',
    '...oo..oo...',
  ],
  robe: [
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '..oooooooo..',
    '..oOooooOo..',
    '..oooooooo..',
    '..oooooooo..',
    '.oooooooooo.',
    '.oOOooooOOo.',
    '.oooooooooo.',
  ],
  cape: [
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '.OoooooooooO',
    '.O.oooooo.O.',
    '.O.oOOOOo.O.',
    '.O..oooo..O.',
    '.OO.o..o.OO.',
  ],
};

// ————— Ennemis (palette fixe par type) —————

export interface EnemySpriteDef {
  map: PixelMap;
  palette: Record<string, string>;
}

export const ENEMY_SPRITES: Record<string, EnemySpriteDef> = {
  slime: {
    palette: { b: '#5cb85c', B: '#3e8e41', k: '#1c3320', w: '#eaffea' },
    map: [
      '............',
      '...kkkkkk...',
      '..kbbbbbbk..',
      '.kbbbbbbbbk.',
      '.kbwbbbbwbk.',
      'kbbbbbbbbbbk',
      'kbBbbbbbbBbk',
      '.kBBbbbbBBk.',
      '..kkkkkkkk..',
    ],
  },
  goblin: {
    palette: { b: '#8fae4e', B: '#66802f', k: '#232d12', w: '#f4ffdd', x: '#c23b22' },
    map: [
      '.k........k.',
      'kbk......kbk',
      '.kbkkkkkkbk.',
      '..kbbbbbbk..',
      '..kbwbbwbk..',
      '..kbbxxbbk..',
      '...kbbbbk...',
      '..kbbbbbbk..',
      '.kb.bbbb.bk.',
      '..k.bbbb.k..',
      '...kb..bk...',
      '...kk..kk...',
    ],
  },
  cultist: {
    palette: { b: '#6d4a9e', B: '#4a3070', k: '#221438', w: '#ffd76a' },
    map: [
      '....kkkk....',
      '...kbbbbk...',
      '..kbbbbbbk..',
      '..kBwBBwBk..',
      '..kBBBBBBk..',
      '...kbbbbk...',
      '..kbbbbbbk..',
      '..kbbbbbbk..',
      '.kbbbbbbbbk.',
      '.kbbBbbBbbk.',
      '.kbbbbbbbbk.',
      '..kkkkkkkk..',
    ],
  },
  shaman: {
    palette: { b: '#2e8b8b', B: '#1e5f5f', k: '#0f2727', w: '#e8fff9', x: '#d8a03c' },
    map: [
      '.x..kkkk....',
      '.x.kbbbbk...',
      '.x.kbwbwbk..',
      '.xkbbbbbbk..',
      '.x.kbbbbk...',
      '.x.kbbbbk...',
      '.xkbbbbbbk..',
      '.xkbbbbbbk..',
      '.xkbBbbBbk..',
      '.x.kbbbbk...',
      '...kb..bk...',
      '...kk..kk...',
    ],
  },
  // ————— Forêt —————
  wolf: {
    palette: { b: '#9aa3ad', B: '#6b737d', k: '#22262b', w: '#f4f7fa', x: '#c23b22' },
    map: [
      '.k........k.',
      'kbk......kbk',
      'kbbk....kbbk',
      '.kbbkkkkbbk.',
      '.kbbbbbbbbk.',
      '.kbwbbbbwbk.',
      '..kbbbbbbk..',
      '..kbBxxBbk..',
      '...kbbbbk...',
      '...kk..kk...',
    ],
  },
  spider: {
    palette: { b: '#4a3b6b', B: '#332849', k: '#141020', w: '#d6ff5c', x: '#7ee04e' },
    map: [
      '.k..k..k..k.',
      '..k.k..k.k..',
      '..kkkkkkkk..',
      '.kbbbbbbbbk.',
      'kbbwbbbbwbbk',
      'kbbbbxxbbbbk',
      '.kbBbbbbBbk.',
      '..kkkkkkkk..',
      '.k..k..k..k.',
    ],
  },
  dryad: {
    palette: { b: '#7bbf6a', B: '#4e8f43', k: '#1f3318', w: '#fff7e0', x: '#8a5a2b' },
    map: [
      '...kkkkkk...',
      '..kbbbbbbk..',
      '.kbbbbbbbbk.',
      '.kbwbbbbwbk.',
      '..kbbbbbbk..',
      '...kxxxxk...',
      '..kxxxxxxk..',
      '..kxBxxBxk..',
      '..kxxxxxxk..',
      '...kxxxxk...',
      '...kx..xk...',
      '...kk..kk...',
    ],
  },
  ancient_treant: {
    palette: { b: '#6e4a2f', B: '#4a3120', k: '#1d1207', w: '#ffd75e', x: '#5f9e4a' },
    map: [
      '..xx.xxxx.xx....',
      '.xxxxxxxxxxxx...',
      '.xxxxxxxxxxxx...',
      '..xxkkkkkkxx....',
      '..kbbbbbbbbk....',
      '.kbbwbbbbwbbk...',
      '.kbbbbbbbbbbk...',
      '..kbbkkkkbbk....',
      '.kbbbbbbbbbbk...',
      'kbbkbbbbbbkbbk..',
      'kbbkbbbbbbkbbk..',
      'kBBkbBbbBbkBBk..',
      '.kk.bbbbbb.kk...',
      '....kbbbbk......',
      '...kbb..bbk.....',
      '...kkk..kkk.....',
    ],
  },

  // ————— Château —————
  skeleton: {
    palette: { b: '#e8e6da', B: '#b8b5a2', k: '#2a2a24', w: '#1b1b16' },
    map: [
      '...kkkkkk...',
      '..kbbbbbbk..',
      '..kbwbbwbk..',
      '..kbbbbbbk..',
      '...kbkkbk...',
      '..kbbbbbbk..',
      '.kb.kbbk.bk.',
      '.kb.kbbk.bk.',
      '..k.kbbk.k..',
      '....kbbk....',
      '...kb..bk...',
      '...kk..kk...',
    ],
  },
  skeleton_archer: {
    palette: { b: '#e8e6da', B: '#b8b5a2', k: '#2a2a24', w: '#1b1b16', x: '#8a5a2b' },
    map: [
      '...kkkkkk..x',
      '..kbbbbbbk.x',
      '..kbwbbwbkx.',
      '..kbbbbbbkx.',
      '...kbkkbkx..',
      '..kbbbbbkx..',
      '.kb.kbbkxx..',
      '.kb.kbbk.x..',
      '..k.kbbk.x..',
      '....kbbk..x.',
      '...kb..bk.x.',
      '...kk..kk..x',
    ],
  },
  dark_knight: {
    palette: { b: '#5a6273', B: '#3a4150', k: '#161a22', w: '#cc3333', x: '#8f2f2f' },
    map: [
      '....xxxx....',
      '...kkkkkk...',
      '..kbbbbbbk..',
      '..kBwBBwBk..',
      '..kbbbbbbk..',
      '...kbbbbk...',
      '.kkbbbbbbkk.',
      '.kbkbbbbkbk.',
      '.kbkbBBbkbk.',
      '..kkbbbbkk..',
      '...kb..bk...',
      '...kk..kk...',
    ],
  },
  necromancer: {
    palette: { b: '#3f4a3a', B: '#2a3227', k: '#101510', w: '#b7ff9e', x: '#e8e6da' },
    map: [
      '.x..kkkk....',
      'xxx.kbbbbk..',
      '.x.kbbbbbbk.',
      '.x.kBwBBwBk.',
      '.x.kBBBBBBk.',
      '.x..kbbbbk..',
      '.x.kbbbbbbk.',
      '.x.kbbbbbbk.',
      '.xkbbbbbbbbk',
      '.xkbbBbbBbbk',
      '.x.kbbbbbbk.',
      '...kkkkkkkk.',
    ],
  },
  skeleton_king: {
    palette: { b: '#e8e6da', B: '#b8b5a2', k: '#2a2a24', w: '#1b1b16', x: '#d8a03c' },
    map: [
      '..x.x.xx.x.x....',
      '..xxxxxxxxxx....',
      '..kkkkkkkkkk....',
      '.kbbbbbbbbbbk...',
      '.kbbwbbbbwbbk...',
      '.kbbbbbbbbbbk...',
      '..kbbkkkkbbk....',
      '..kkbbbbbbkk....',
      '.kb.kbbbbk.bk...',
      '.kb.kbbbbk.bk...',
      '..k.kbBBbk.k....',
      '....kbbbbk......',
      '...kbb..bbk.....',
      '...kkk..kkk.....',
    ],
  },

  // ————— Volcan —————
  imp: {
    palette: { b: '#c2543a', B: '#8f3a26', k: '#2b0f08', w: '#ffe08a', x: '#5c1e10' },
    map: [
      '.k...kk...k.',
      'kxk..kk..kxk',
      '.kkkkkkkkkk.',
      '..kbbbbbbk..',
      '..kbwbbwbk..',
      '..kbbxxbbk..',
      '...kbbbbk...',
      '..kb.bb.bk..',
      '...kb..bk...',
      '...kk..kk...',
    ],
  },
  magma_slime: {
    palette: { b: '#e0703a', B: '#a34617', k: '#33130a', w: '#ffe9a8' },
    map: [
      '............',
      '...kkkkkk...',
      '..kbbbbbbk..',
      '.kbbbbbbbbk.',
      '.kbwbbbbwbk.',
      'kbbbbbbbbbbk',
      'kbBbbbbbbBbk',
      '.kBBbbbbBBk.',
      '..kkkkkkkk..',
    ],
  },
  golem: {
    palette: { b: '#7a6f66', B: '#544b43', k: '#1e1a16', w: '#ff9a3c', x: '#e0703a' },
    map: [
      '..kkkkkkkk..',
      '.kbbbbbbbbk.',
      '.kbwbbbbwbk.',
      '.kbbbxxbbbk.',
      '..kbbbbbbk..',
      '.kkbbbbbbkk.',
      'kbbkbbbbkbbk',
      'kbbkbxxbkbbk',
      'kBBkbbbbkBBk',
      '.kk.kbbk.kk.',
      '...kbb.bbk..',
      '...kkk.kkk..',
    ],
  },
  fire_demon: {
    palette: { b: '#c2543a', B: '#8f3a26', k: '#2b0f08', w: '#ffe08a', x: '#ffb13c' },
    map: [
      '.k....kk....k...',
      'kxk...kk...kxk..',
      '.kkkkkkkkkkkk...',
      '..kbbbbbbbbk....',
      '.kbbwbbbbwbbk...',
      '.kbbbbxxbbbbk...',
      '..kbbbbbbbbk....',
      'kk.kbbkkbbk..kk.',
      'kbkkbbbbbbkkkbk.',
      'kbbkbbbbbbkbbbk.',
      '.kkkbBbbBbkkkk..',
      '....kbbbbk......',
      '....kbbbbk......',
      '...kbb..bbk.....',
      '...kkk..kkk.....',
    ],
  },
};
